### ISSUE TITLE
http://purl.org/lobid/nwbib#s798010 missing in vocab

### ISSUE THREAD

**Issue by fsteeg** [lobid/vocabs#30]
Used in http://lobid.org/resource?id=HT016837061&format=full

**Comment by acka47** [comment]
With https://github.com/hbz/nwbib/commit/df61371aee70e3c612fe84d60a4e967b7d0cc64c we can now easily see in http://lobid.org/nwbib which notations are used without being part of the vocab and how many titles are associated with each one.

**Comment by acka47** [comment]
Sent a mail to the mailing list asking NWBib editors to remove these notations from the source data.

**Comment by acka47** [comment]
Many of the notations are already removed, some are still there so that I leave the issue open.

**Comment by acka47** [comment]
Currently, there are no "pseudo" notations in the data. Probably we will get a data validation into Aleph in the future so that such notations can't be saved at all. Closing.
