### ISSUE TITLE
Create class lv:Anthology

### ISSUE THREAD

**Issue by acka47** [lobid/vocabs#37]
We need a class to type anthologies (Sammelbände).

**Comment by acka47** [comment]
See https://github.com/lobid/lodmill/issues/271#issuecomment-73509728.

**Comment by acka47** [comment]
After some research and [asking on twitter](https://twitter.com/acka47/status/564786899341279232) I decided that `lv:EditedVolume` is the more appropriate term.

**Comment by dr0i** [comment]
Class is created, closing.
