### ISSUE TITLE
Create specific properties for isPart relations

### ISSUE THREAD

**Issue by acka47** [lobid/vocabs#39]
See https://github.com/lobid/lodmill/issues/497#issuecomment-121547943 where it reads:

> - volumes of a series (example: http://lobid.org/nwbib/HT015563767; [morph, line 63](https://github.com/lobid/lodmill/blob/f2813be35af1b56cc9812377e86031661c2efb09/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L63)), 
- a volume of a multi-volume book (example: http://lobid.org/nwbib/HT017847410; [morph, line 65](https://github.com/lobid/lodmill/blob/f2813be35af1b56cc9812377e86031661c2efb09/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L65)) and
- articles in a journal, edited volume etc. (examples: http://lobid.org/nwbib/HT017306644, http://lobid.org/nwbib/HT018408723; [morph, line 1233](https://github.com/lobid/lodmill/blob/f2813be35af1b56cc9812377e86031661c2efb09/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1233)) 

We should use a level of indirection for the first two as drafted in https://github.com/lobid/lodmill/issues/497#issuecomment-71481538. Thus, we will have to add at least four properties...

**Comment by acka47** [comment]
Here is the newest suggestion. What do others think?

```javascript
{
    "@id" : "http://lobid.org/resource/HT017903191",
     "volumeIn" : {
              "multiVolumeWork": "http://lobid.org/resource/HT007384038", 
              "numbering": "10"
     },
     "inSeries" : {
              "series": "http://lobid.org/resource/HT003613090", 
              "numbering": "52"
     }
}
```

**Comment by acka47** [comment]
@literarymachine indicated that a type for the part-to-MutliVolumeWork/Series-relation (as `rdfs:range` in the vocab and added to lobid data) is needed for editing purposes in edoweb. Considering this, I suggest:

```javascript
{
    "@id" : "http://lobid.org/resource/HT017903191",
     "volumeIn" : {
             "@type": "http://purl.org/lobid/lv#MultiVolumeWorkRelation",
              "multiVolumeWork": "http://lobid.org/resource/HT007384038", 
              "numbering": "10"
     },
     "inSeries" : {
             "@type": "http://purl.org/lobid/lv#SeriesRelation"
              "series": "http://lobid.org/resource/HT003613090", 
              "numbering": "52"
     }
}
```

What do you think, @literarymachine ?

**Comment by acka47** [comment]
As written in lobid/lodmill/#702, for linking articles to a journal or edited volume the property `lv:containedIn` has to be added.

**Comment by literarymachine** [comment]
Seems reasonable! I could also enrich those types internally, but I do believe that a shared vocabulary is the way to go.

**Comment by dr0i** [comment]
+1
