### ISSUE TITLE
Use w3id instead of purl.org

### ISSUE THREAD

**Issue by acka47** [lobid/vocabs#50]
Currently, we use PURLs as identifiers for nearly all our vocabs (except https://github.com/lobid/vocabs/blob/master/rpb/rpb2.ttl). As purl.org isn't curated anymore and we can't adjust the redirects, we might move to w3id in the context of switching to lobid API 2.0.

**Comment by acka47** [comment]
purl.org is now managed by the Internet Archive. I don't see why we should put more trust in w3id than in purl/Internet Archive and suggest that we stay with purl.org. @dr0i please close this issue if you agree.

**Comment by dr0i** [comment]
Ack for now, no more pressure to change things. Closing.
